export const PLATFORM_ENV_PREFIX = 'PLATFORM_' as const;
export const PLATFORM_ORIGIN_VERIFY_HEADER_NAME = 'PLATFORM_ORIGIN_VERIFY_HEADER_NAME' as const;
export const PLATFORM_ORIGIN_VERIFY_HEADER_VALUE_SSM_PARAM_ARN =
  'PLATFORM_ORIGIN_VERIFY_HEADER_VALUE_SSM_PARAM_ARN' as const;
export const PLATFORM_CSRF_COOKIE_NAME = 'PLATFORM_CSRF_COOKIE_NAME' as const;
export const PLATFORM_CSRF_HEADER_NAME = 'PLATFORM_CSRF_HEADER_NAME' as const;
